### ISSUE TITLE
The addEditDBForm No longer validates the form

### ISSUE THREAD

**Issue by noombi** [WaSQL/v2#1]
I am able to submit forms without entering in required fields. Is there a way to bring back this functionality?

**Comment by slloyd88** [comment]
can you send me your page source and any error messages you find in the developer console?
Also, when is the last time you did a git pull?

**Comment by noombi** [comment]
Last pull that I did was yesterday. I don't receive any console errors. Also there seems to be something up with postedit. Let me know if I can help in anyway!

[stage.ubinternet.com.zip](https://github.com/WaSQL/v2/files/1145908/stage.ubinternet.com.zip)

**Comment by slloyd88** [comment]
Should be fixed - do another pull.  Call me on the postedit thing.
